lan:
  interface_interna: eth1
  ip_externo: 192.168.0.60
  ip_administrador: 192.168.0.2
  interface_externa: eth0
  red_interna: 10.39.65.0/24
  red_externa: 192.168.0.0/24
  ip_interno: 10.39.65.1

bandwidht:
  medium_ceil: 256
  low_ceil: 128
  total_subida: 2048
  high_ceil: 384
  total_bajada: 2048
  porcentaje_rate: 80
  puertos_priorizados: 22,23,80,443,1863,3389,5223
  full_ceil: 512